# -*- mode: ruby -*-
# vi: set ft=ruby :


VM_BOX = "ubuntu/groovy64"
PROVIDER = "virtualbox"
DOMAIN_NAME = "cluster"
# configure network subnet in virtualbox, here is vbox0
NETWORK_SUBNET = "192.168.56"
SERVER_HOST_IPS_START = 10
SERVER_MEMORY = "1024"
WORKER_HOST_IPS_START = 100
WORKER_MEMORY = "1024"
NUM_SERVER_NODES = 3
NUM_WORKER_NODES = 3
NUM_GW_NODES = 1
ENABLE_VB_GUI = true
LINK_CLONES = true

Vagrant.configure("2") do |config|


  (1..NUM_SERVER_NODES).each do |n|
    config.vm.define "consul#{n}.#{DOMAIN_NAME}" do |srv|
      srv.vm.hostname = "consul#{n}.#{DOMAIN_NAME}"
      srv.vm.network :private_network, ip: "#{NETWORK_SUBNET}.#{SERVER_HOST_IPS_START + n}"


      srv.vm.box = VM_BOX
      srv.vm.provider PROVIDER do |provider|
     # Display the VirtualBox GUI when booting the machine
          provider.gui = ENABLE_VB_GUI
          provider.memory = SERVER_MEMORY
          provider.linked_clone = LINK_CLONES
      end
    end
  end


  (1..NUM_WORKER_NODES).each do |n|
    config.vm.define "worker#{n}.#{DOMAIN_NAME}" do |wrk|
      wrk.vm.hostname = "worker#{n}.#{DOMAIN_NAME}"
      wrk.vm.network :private_network, ip: "#{NETWORK_SUBNET}.#{WORKER_HOST_IPS_START + n}"


      wrk.vm.box = VM_BOX
      wrk.vm.provider PROVIDER do |provider|
     # Display the VirtualBox GUI when booting the machine
          provider.gui = ENABLE_VB_GUI
          provider.memory = WORKER_MEMORY
          provider.linked_clone = LINK_CLONES
      end
    end
  end

end
