---
# tasks file for common
# tasks file for common 
- name: Upgrade system
  apt:
    upgrade: yes
  ignore_errors: yes

- name: Install required packages
  apt: 
    name: "{{ apt_packages }}" 
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes
 
  ignore_errors: yes


- name: Disable systemd-resolved 
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Install Docker on workers
  apt: 
    name: docker.io
    state: present
  when: "'worker' in inventory_hostname"